keymint: introduce TagType::BIGNUM
Rename to BIGNUM_ to avoid conflict name in openssl/base.h

```
test/system-test-harness/src/keymaster-import-key-tests.cc:465:9: error: reference to 'BIGNUM' is ambiguous
  const BIGNUM *d = EC_KEY_get0_private_key(ec.get());
        ^
external/boringssl_git/src/include/openssl/base.h:369:26: note: candidate found by name lookup is 'BIGNUM'
typedef struct bignum_st BIGNUM;
```

Change-Id: If4088141b35259c375c1abba7b84ae4851ebeccd
Reviewed-on: https://nugget-os-review.googlesource.com/c/host/generic/+/42804
Tested-by: Tommy Chiu <tommychiu@google.com>
Presubmit-Verified: TreeHugger Robot <android-build-prod@system.gserviceaccount.com>
Reviewed-by: Tommy Chiu <tommychiu@google.com>
Reviewed-by: I-Chih Lu <ichihlu@google.com>